# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_SignUpForm(object):
    def setupUi(self, SignUpForm):
        SignUpForm.setObjectName("SignUpForm")
        SignUpForm.resize(403, 412)
        self.centralwidget = QtWidgets.QWidget(SignUpForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(141, 41))
        self.label.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMinimumSize(QtCore.QSize(368, 0))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setMinimumSize(QtCore.QSize(368, 0))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        SignUpForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignUpForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 26))
        self.menubar.setObjectName("menubar")
        SignUpForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignUpForm)
        self.statusbar.setObjectName("statusbar")
        SignUpForm.setStatusBar(self.statusbar)

        self.retranslateUi(SignUpForm)
        QtCore.QMetaObject.connectSlotsByName(SignUpForm)
        self.pushButton.clicked.connect(self.setMasterPassword)

    """
    For setting master password. All necessary checks are done!
    """

    def setMasterPassword(self):
        with open("passwords/jsons.json", 'r') as f:
            data = json.load(f)
        if(data[0]['crypticMasterPass'] == "" and self.textEdit.toPlainText() != ""):
            if(self.textEdit.toPlainText() == self.textEdit_2.toPlainText()):
                data[0]['crypticMasterPass'] = self.textEdit_2.toPlainText()
                newMasterPassword = data[0]['crypticMasterPass']
                data.append(newMasterPassword)
                with open('passwords/jsons.json', 'w') as f:
                    json.dump(data, f)
            else:
                print("Passwords don't match")
        else:
            print('Master password already set, cannot continue')

    def retranslateUi(self, SignUpForm):
        _translate = QtCore.QCoreApplication.translate
        SignUpForm.setWindowTitle(_translate("SignUpForm", "MainWindow"))
        self.label.setText(_translate("SignUpForm", "Sign Up"))
        self.label_2.setText(_translate("SignUpForm", "Enter a new password:"))
        self.label_4.setText(_translate("SignUpForm", "Confirm new password"))
        self.label_3.setText(_translate(
            "SignUpForm", "NOTE: Your password can be as long as you want, and if you lose this password, you won\'t be able to access your account again"))
        self.pushButton.setText(_translate(
            "SignUpForm", "Set master password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpForm = QtWidgets.QMainWindow()
    ui = Ui_SignUpForm()
    ui.setupUi(SignUpForm)
    SignUpForm.show()
    sys.exit(app.exec_())
