# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signInPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from startPage import Ui_PasswordManager as psdd
import startPage


class Ui_SignInPage(object):
    def setupUi(self, SignInPage):
        SignInPage.setObjectName("SignInPage")
        SignInPage.resize(501, 428)
        self.centralwidget = QtWidgets.QWidget(SignInPage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(251, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(71, 16))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(113, 22))
        self.lineEdit.setMaximumSize(QtCore.QSize(211, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(71, 16))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(113, 22))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(211, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(93, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        SignInPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignInPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 26))
        self.menubar.setObjectName("menubar")
        SignInPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignInPage)
        self.statusbar.setObjectName("statusbar")
        SignInPage.setStatusBar(self.statusbar)

        self.retranslateUi(SignInPage)
        QtCore.QMetaObject.connectSlotsByName(SignInPage)

        self.pushButton_2.clicked.connect(self.backToHomeScreen)
        self.pushButton.clicked.connect(self.toMainMenu)

    def retranslateUi(self, SignInPage):
        _translate = QtCore.QCoreApplication.translate
        SignInPage.setWindowTitle(_translate("SignInPage", "MainWindow"))
        self.label.setText(_translate(
            "SignInPage", "Log in with your credentials"))
        self.label_2.setText(_translate("SignInPage", "Username"))
        self.label_3.setText(_translate("SignInPage", "Password"))
        self.pushButton.setText(_translate("SignInPage", "Sign in"))
        self.pushButton_2.setText(_translate("SignInPage", "Back"))

    def toMainMenu(self):
        # TODO code for decypting the JSON file.
        print("Going to Main screen after sign up")
        pass

    def backToHomeScreen(self):
        print("Going back to homescreen")
        SignInPage.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = startPage.Ui_PasswordManager()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignInPage = QtWidgets.QMainWindow()
    ui = Ui_SignInPage()
    ui.setupUi(SignInPage)
    SignInPage.show()
    sys.exit(app.exec_())
