# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUpPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import path
import securityUtils as sec
import startPage


class Ui_SignUpPage(object):
    def setupUi(self, SignUpPage):
        SignUpPage.setObjectName("SignUpPage")
        SignUpPage.resize(528, 449)
        self.centralwidget = QtWidgets.QWidget(SignUpPage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(251, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(71, 16))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(71, 16))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(93, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        SignUpPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignUpPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 26))
        self.menubar.setObjectName("menubar")
        SignUpPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignUpPage)
        self.statusbar.setObjectName("statusbar")
        SignUpPage.setStatusBar(self.statusbar)

        self.retranslateUi(SignUpPage)
        QtCore.QMetaObject.connectSlotsByName(SignUpPage)
        self.pushButton.clicked.connect(self.toMainscreen)
        self.pushButton_2.clicked.connect(self.backToHomeScreen)

    def retranslateUi(self, SignUpPage):
        _translate = QtCore.QCoreApplication.translate
        SignUpPage.setWindowTitle(_translate("SignUpPage", "MainWindow"))
        self.label.setText(_translate("SignUpPage", "Sign Up here"))
        self.label_2.setText(_translate("SignUpPage", "Username"))
        self.label_3.setText(_translate("SignUpPage", "Password"))
        self.pushButton.setText(_translate("SignUpPage", "Sign up"))
        self.pushButton_2.setText(_translate("SignUpPage", "Back"))

    def backToHomeScreen(self):
        print("Going back to homescreen")
        SignUpPage.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = startPage.Ui_PasswordManager()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def toMainscreen(self):
        
        # Code for creating the JSON file when user logs in for the first time. 
        if not path.isfile('../passwords/user.json'):
            with open('../passwords/user.json', 'x') as f:
                pass
        else:
            # File already exists, so user signed up previously.
            print("You have already signed up")     # TODO Make a dialog box with this message and go to log in screen

            # TODO Remove later and put the following code when the user logs out / closes the app. 
            # This is here for testing purposes.
            
            # Get username and passwords from the text fields
            username = self.lineEdit.text()
            password = self.lineEdit_2.text()
            
            # Initializing the Fernet key to decrypt the user's JSON file
            key = sec.create_key(username, password)

            # Encrypting the user's JSON file
            sec.encrypt(key)

        print("Going to Main screen after sign up")
        
        # TODO Go back to main screen  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpPage = QtWidgets.QMainWindow()
    ui = Ui_SignUpPage()
    ui.setupUi(SignUpPage)
    SignUpPage.show()
    sys.exit(app.exec_())
