# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import 2nd screen
import signInPage
import signUpPage


class Ui_PasswordManager(object):
    def setupUi(self, PasswordManager):
        PasswordManager.setObjectName("PasswordManager")
        PasswordManager.resize(629, 453)
        PasswordManager.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(PasswordManager)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setMinimumSize(QtCore.QSize(0, 0))
        self.label1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setKerning(True)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setMinimumSize(QtCore.QSize(0, 0))
        self.label2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setMinimumSize(QtCore.QSize(0, 0))
        self.button1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.gridLayout_2.addWidget(self.button1, 0, 0, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.gridLayout_2.addWidget(self.button2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        PasswordManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PasswordManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PasswordManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PasswordManager)
        self.statusbar.setObjectName("statusbar")
        PasswordManager.setStatusBar(self.statusbar)
        self.actionEXIT = QtWidgets.QAction(PasswordManager)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuFile.addAction(self.actionEXIT)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PasswordManager)
        QtCore.QMetaObject.connectSlotsByName(PasswordManager)
        self.retranslateUi(PasswordManager)
        QtCore.QMetaObject.connectSlotsByName(PasswordManager)
        # for master password screen
        self.button1.clicked.connect(self.secondscr)
        # for the sign up page screen
        self.button2.clicked.connect(self.signUpScr)

        self.actionEXIT.triggered.connect(QtWidgets.QApplication.quit)

    def secondscr(self):
        # code the 2nd screen here
        PasswordManager.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = signInPage.Ui_SignInPage()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def signUpScr(self):
        PasswordManager.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = signUpPage.Ui_SignUpPage()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def retranslateUi(self, PasswordManager):
        _translate = QtCore.QCoreApplication.translate
        PasswordManager.setWindowTitle(
            _translate("PasswordManager", "MainWindow"))
        self.label1.setText(_translate("PasswordManager", "PASSWORD MANAGER"))
        self.label2.setText(_translate("PasswordManager", "- HW Tech Club"))
        self.button1.setText(_translate("PasswordManager", "Login"))
        self.button2.setText(_translate("PasswordManager", "Sign up"))
        self.menuFile.setTitle(_translate("PasswordManager", "File"))
        self.actionEXIT.setText(_translate("PasswordManager", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordManager = QtWidgets.QMainWindow()
    ui = Ui_PasswordManager()
    ui.setupUi(PasswordManager)
    PasswordManager.show()
    sys.exit(app.exec_())
