# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordManager(object):
    def setupUi(self, PasswordManager):
        PasswordManager.setObjectName("PasswordManager")
        PasswordManager.resize(754, 589)
        PasswordManager.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(PasswordManager)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 60, 511, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label1.setMinimumSize(QtCore.QSize(0, 0))
        self.label1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setKerning(True)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label2.setMinimumSize(QtCore.QSize(0, 0))
        self.label2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(170, 340, 411, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button1.setMinimumSize(QtCore.QSize(0, 0))
        self.button1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.gridLayout_2.addWidget(self.button1, 0, 0, 1, 1)
        PasswordManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PasswordManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PasswordManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PasswordManager)
        self.statusbar.setObjectName("statusbar")
        PasswordManager.setStatusBar(self.statusbar)
        self.actionEXIT = QtWidgets.QAction(PasswordManager)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuFile.addAction(self.actionEXIT)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PasswordManager)
        QtCore.QMetaObject.connectSlotsByName(PasswordManager)

    def retranslateUi(self, PasswordManager):
        _translate = QtCore.QCoreApplication.translate
        PasswordManager.setWindowTitle(_translate("PasswordManager", "MainWindow"))
        self.label1.setText(_translate("PasswordManager", "PASSWORD MANAGER"))
        self.label2.setText(_translate("PasswordManager", "- HW Tech Club"))
        self.button1.setText(_translate("PasswordManager", "Start"))
        self.menuFile.setTitle(_translate("PasswordManager", "File"))
        self.actionEXIT.setText(_translate("PasswordManager", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordManager = QtWidgets.QMainWindow()
    ui = Ui_PasswordManager()
    ui.setupUi(PasswordManager)
    PasswordManager.show()
    sys.exit(app.exec_())
