# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_ViewPassword(object):
    def setupUi(self, ViewPassword):
        ViewPassword.setObjectName("ViewPassword")
        ViewPassword.resize(626, 520)
        self.centralwidget = QtWidgets.QWidget(ViewPassword)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(71, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            605, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(81, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(71, 31))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(
            605, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        ViewPassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ViewPassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 26))
        self.menubar.setObjectName("menubar")
        ViewPassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ViewPassword)
        self.statusbar.setObjectName("statusbar")
        ViewPassword.setStatusBar(self.statusbar)
        self.tableWidget.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch)
        self.retranslateUi(ViewPassword)
        QtCore.QMetaObject.connectSlotsByName(ViewPassword)
        self.pushButton.clicked.connect(self.loadTableData)
        # self.pushButton_2.clicked.connect(self.goBack)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)  # to disable table editing.
    """
    to load the username, pwd and notes from the json file into the Table widget.
    """

    def loadTableData(self):
        with open("../passwords/user.json", "r") as read:
            data = json.load(read)

        # to reset table eveytime this button is clicked.
        self.tableWidget.setRowCount(0)

        row = 0
        self.tableWidget.setRowCount(len(data))
        for userData in data:
            if(userData['site'] == self.lineEdit.text()):
                print(userData)
                self.tableWidget.setItem(
                    row, 0, QtWidgets.QTableWidgetItem(userData["user"]))
                self.tableWidget.setItem(
                    row, 1, QtWidgets.QTableWidgetItem(userData["pwd"]))
                self.tableWidget.setItem(
                    row, 2, QtWidgets.QTableWidgetItem(userData["notes"]))
                row = row+1

    def retranslateUi(self, ViewPassword):
        _translate = QtCore.QCoreApplication.translate
        ViewPassword.setWindowTitle(_translate("ViewPassword", "MainWindow"))
        self.pushButton_2.setText(_translate("ViewPassword", "Go Back"))
        self.label.setText(_translate("ViewPassword", "View Passwords"))
        self.label_2.setText(_translate("ViewPassword", "Site name"))
        self.pushButton.setText(_translate("ViewPassword", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewPassword", "Usernames"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewPassword", "Passwords"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ViewPassword", "Notes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewPassword = QtWidgets.QMainWindow()
    ui = Ui_ViewPassword()
    ui.setupUi(ViewPassword)
    ViewPassword.show()
    sys.exit(app.exec_())
